// <auto-generated/>

namespace HexedTest.Library.Api.Extensions;

public static class WebApplicationExtensions
{
    /// <summary>
    /// Register the routes within the application making them available for HTTP requests.
    /// </summary>
    /// <param name="app"></param>
    public static void RegisterRoutes(this WebApplication app)
    {
        app.MapControllers();
    }


    /// <summary>
    /// Gets the LibraryContext and runs EFCore EnsureCreated method.
    /// </summary>
    /// <param name="app"></param>
    public static void EnsureDbIsCreated(this WebApplication app)
    {
        using IServiceScope scope = app.Services.CreateScope();
        LibraryContext context = scope.ServiceProvider.GetService<LibraryContext>();
        context.Database.EnsureCreated();
        context.Dispose();
    }
}